/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pantallas;

import Sockets.Mensaje;
import Sockets.SocketCliente;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author nomar
 */
<<<<<<< Updated upstream:BattleshipVista/src/main/java/pantallas/FrmJugadorUno.java
public class FrmJugadorUno extends javax.swing.JFrame {
    // Cliente socket para comunicación con el servidor
=======
public class NomJugador1 extends javax.swing.JFrame {
>>>>>>> Stashed changes:BattleshipVista/src/main/java/pantallas/NomJugador1.java

    private SocketCliente cliente;
  /**
     * Constructor de la clase FrmJugadorUno.
     * Inicializa los componentes gráficos de la ventana.
     */
    /**
     * Creates new form FrmJugadorUno
     */
    public NomJugador1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnListo = new javax.swing.JLabel();
        campoTextoUsuarioUno = new javax.swing.JTextField();
        btnAtras = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnListo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btnListo.png"))); // NOI18N
        btnListo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnListo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnListoMouseClicked(evt);
            }
        });
        getContentPane().add(btnListo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 150, -1));

        campoTextoUsuarioUno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTextoUsuarioUnoActionPerformed(evt);
            }
        });
        getContentPane().add(campoTextoUsuarioUno, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 130, 30));

        btnAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btnAtras.png"))); // NOI18N
        btnAtras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(btnAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PantallaJugador.png"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoTextoUsuarioUnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTextoUsuarioUnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoTextoUsuarioUnoActionPerformed
 /**
     * Evento que se ejecuta al hacer clic en el botón "Listo".
     * 
     * - Valida que el campo de texto no esté vacío.
     * - Crea la conexión con el servidor (localhost:12345).
     * - Envía el nombre del jugador 1 al servidor en formato JSON.
     * - Recibe el nombre del jugador 2.
     * - Muestra mensaje de conexión exitosa.
     * - Abre la ventana para colocar las naves (ColocarNave2).
     * - Cierra esta ventana.
     * 
     * En caso de error muestra mensaje y re-habilita el botón.
     */
    private void btnListoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListoMouseClicked
        // TODO add your handling code here:
        try {
            btnListo.setEnabled(false);
            cliente = new SocketCliente();
            cliente.conectar("127.0.0.1", 12345);

            String nombreJugador1 = campoTextoUsuarioUno.getText().trim();
            if (nombreJugador1.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Ingresa tu nombre.");
                btnListo.setEnabled(true);
                return;
            }

            // Enviar el nombre del jugador 1 al servidor en un mensaje JSON
            Mensaje mensajeNombre = new Mensaje("nombre", nombreJugador1);
            cliente.enviarMensaje(mensajeNombre);

            // Recibir el nombre del jugador 2 desde el servidor
            Mensaje mensajeRecibido = cliente.recibirMensaje();
            Object nombreRival = mensajeRecibido.getContenido().toString();

            JOptionPane.showMessageDialog(this, "Conectado con: " + nombreRival);

<<<<<<< Updated upstream:BattleshipVista/src/main/java/pantallas/FrmJugadorUno.java
            // Abrir ventana para colocar las naves
            ColocarNave2 ventana = new ColocarNave2(nombreJugador1, cliente);
            ventana.setLocation(10, 250);
            ventana.setVisible(true);
            dispose();
=======
        

        // Abrir ventana para colocar las naves
        CrearTablero ventana = new CrearTablero(nombreJugador1, cliente);
        ventana.setLocation(10, 250);
        ventana.setVisible(true);
        dispose();
>>>>>>> Stashed changes:BattleshipVista/src/main/java/pantallas/NomJugador1.java

        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error al conectar: " + e.getMessage());
            e.printStackTrace();
            btnListo.setEnabled(true);
        }
    }//GEN-LAST:event_btnListoMouseClicked

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(NomJugador1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(NomJugador1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(NomJugador1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(NomJugador1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new NomJugador1().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnAtras;
    private javax.swing.JLabel btnListo;
    private javax.swing.JTextField campoTextoUsuarioUno;
    private javax.swing.JLabel fondo;
    // End of variables declaration//GEN-END:variables
}
